### ISSUE TITLE
Markdown To-Do List Not Formatting Correctly

### ISSUE THREAD

**Issue by jq-11** [rstudio/bookdown#1482]
Hello!

Here is a super small but weird bug.

Markdown creates to-do lists as follows:

```
- [ ] unchecked to-do 
- [x] checked to-do 
```

and the output looks like this:

- [ ] unchecked to-do 
- [x] checked to-do

Weirdly enough, in a bookdown .Rmd, the output looks slightly different:

```
- [ ] unchecked to-do 
- [x] checked to-do 
```

ends up looking like this

![Image](https://github.com/user-attachments/assets/5ba6de94-d73c-42dc-8994-c00e22dedcdb).

Here is my output for `xfun::session_info('bookdown')`:
```
R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.7.1, RStudio 2024.9.0.375

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3   bookdown_0.41.1   bslib_0.8.0       cachem_1.1.0      cli_3.6.3         digest_0.6.37     evaluate_1.0.1   
  fastmap_1.2.0     fontawesome_0.5.3 fs_1.6.5          glue_1.8.0        graphics_4.4.1    grDevices_4.4.1   highr_0.11       
  htmltools_0.5.8.1 jquerylib_0.1.4   jsonlite_1.8.9    knitr_1.49        lifecycle_1.0.4   memoise_2.0.1     methods_4.4.1    
  mime_0.12         R6_2.5.1          rappdirs_0.3.3    rlang_1.1.4       rmarkdown_2.29    sass_0.4.9        stats_4.4.1      
  tinytex_0.54      tools_4.4.1       utils_4.4.1       xfun_0.49         yaml_2.3.10
```

Similar packages like bookdown (Jupyter Book and Carpentries' templates) had/have similar issues with rendering to-do lists. 

I previously raised this issue to carpentries' formatting package GitHub, and they were able to solve the issue: https://github.com/carpentries/varnish/issues/156.

Thanks for reading! Please help if you can!

Have a great day!

**Comment by jq-11** [comment]
Hi @cderv ! Thanks for the response!

I'm working in the Gitbook bookdown format, but I think this also occurs in the bs4_book as well (although I haven't tested this).

Thanks!
